version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "arkhipova_203"
      POSTGRES_USER: "arkhipova_203"
      POSTGRES_PASSWORD: "arkhipova_203"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
        - ./docker/db/scripts/hospital/hospital.sql:/docker-entrypoint-initdb.d/hospital.sql
        - ./docker/db/scripts/library/library.sql:/docker-entrypoint-initdb.d/library.sql
        - ./docker/db/scripts/trains/trains.sql:/docker-entrypoint-initdb.d/trains.sql
    ports:
      - "5432:5432"
